/**
 * The corpus manifest — the ONE ingest input, converted from the oracle
 * (sor-agentfactory @ b554f91, ingest/manifest.py): `manifest.json` is
 * GENERATED by a corpus adapter at bundle publication; ingest consumes it and
 * never re-derives taxonomy. Every adapter emits this same shape — the kernel
 * cannot tell them apart.
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";

export const SUPPORTED_FORMATS: readonly number[] = [1];

export interface ManifestNode {
  readonly stable_id: string;
  readonly slug: string;
  readonly title: string;
  readonly kind: string;
  /** parent's stable_id; null = root */
  readonly parent: string | null;
  readonly position: number;
  readonly summary: string | null;
  readonly keywords: readonly string[];
  /**
   * The page's site ROUTE, NOT the node slug — the two differ whenever a page
   * carries a frontmatter `slug:`. Present ONLY when the route provably
   * resolves; null = no confirmed page. Never guessed. (Carried for shape
   * fidelity; ksor derives routes from paths, so adapters here leave it null.)
   */
  readonly permalink: string | null;
}

export interface ManifestFile {
  /** bundle-relative markdown path */
  readonly path: string;
  /** owning node's stable_id */
  readonly node: string;
  /** defaults to the node title at build time */
  readonly title: string | null;
}

export interface Manifest {
  readonly format: number;
  readonly corpus_id: string;
  readonly source_commit: string;
  readonly nodes: readonly ManifestNode[];
  readonly files: readonly ManifestFile[];
}

/** The manifest is malformed — named precisely; a bad manifest never half-ingests. */
export class ManifestError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ManifestError";
  }
}

export interface ManifestNodeInit {
  readonly stable_id: string;
  readonly slug: string;
  readonly title: string;
  readonly kind: string;
  readonly parent?: string | null;
  readonly position?: number;
  readonly summary?: string | null;
  readonly keywords?: readonly string[];
  readonly permalink?: string | null;
}

/** Mirrors the oracle dataclass defaults (parent/summary/permalink None, position 0, keywords ()). */
export function manifestNode(init: ManifestNodeInit): ManifestNode {
  return {
    stable_id: init.stable_id,
    slug: init.slug,
    title: init.title,
    kind: init.kind,
    parent: init.parent ?? null,
    position: init.position ?? 0,
    summary: init.summary ?? null,
    keywords: init.keywords ?? [],
    permalink: init.permalink ?? null,
  };
}

export interface ManifestFileInit {
  readonly path: string;
  readonly node: string;
  readonly title?: string | null;
}

export function manifestFile(init: ManifestFileInit): ManifestFile {
  return { path: init.path, node: init.node, title: init.title ?? null };
}

export function parseManifest(text: string): Manifest {
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch (exc) {
    throw new ManifestError(
      `manifest.json is not valid JSON: ${exc instanceof Error ? exc.message : String(exc)}`,
    );
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    throw new ManifestError("manifest.json must be an object");
  }
  const obj = raw as Record<string, unknown>;
  const fmt = obj["format"];
  if (typeof fmt !== "number" || !SUPPORTED_FORMATS.includes(fmt)) {
    throw new ManifestError(
      `manifest format ${JSON.stringify(fmt)} unsupported (supported: ${SUPPORTED_FORMATS.join(", ")})`,
    );
  }
  const corpusId = topString(obj, "corpus_id");
  const sourceCommit = topString(obj, "source_commit");
  const nodes = entriesOf(obj, "nodes").map((n, i) =>
    manifestNode({
      stable_id: req(n, "stable_id", i),
      slug: req(n, "slug", i),
      title: req(n, "title", i),
      kind: req(n, "kind", i),
      parent: optString(n["parent"]),
      position: toPosition(n["position"], i),
      summary: optString(n["summary"]),
      keywords: toKeywords(n["keywords"], i),
      permalink: optString(n["permalink"]),
    }),
  );
  const files = entriesOf(obj, "files").map((f, i) =>
    manifestFile({
      path: req(f, "path", i),
      node: req(f, "node", i),
      title: optString(f["title"]),
    }),
  );
  validate(nodes, files);
  return { format: fmt, corpus_id: corpusId, source_commit: sourceCommit, nodes, files };
}

function topString(obj: Record<string, unknown>, key: string): string {
  const val = obj[key];
  if (typeof val !== "string" || !val) {
    throw new ManifestError(`manifest.${key} must be a non-empty string`);
  }
  return val;
}

function entriesOf(
  obj: Record<string, unknown>,
  key: "nodes" | "files",
): Record<string, unknown>[] {
  const raw = obj[key] ?? [];
  if (!Array.isArray(raw)) throw new ManifestError(`manifest.${key} must be an array`);
  return raw.map((entry: unknown, i: number) => {
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
      throw new ManifestError(`entry ${i}: must be an object`);
    }
    return entry as Record<string, unknown>;
  });
}

function req(obj: Record<string, unknown>, key: string, index: number): string {
  const val = obj[key];
  if (typeof val !== "string" || !val) {
    throw new ManifestError(`entry ${index}: '${key}' must be a non-empty string`);
  }
  return val;
}

function optString(val: unknown): string | null {
  return typeof val === "string" ? val : null;
}

/** Python `int(...)` parity: truncate finite numbers, parse integer strings, refuse the rest loudly. */
function toPosition(val: unknown, index: number): number {
  if (val === undefined) return 0;
  if (typeof val === "number" && Number.isFinite(val)) return Math.trunc(val);
  if (typeof val === "boolean") return val ? 1 : 0;
  if (typeof val === "string" && /^[+-]?\d+$/.test(val.trim()))
    return Number.parseInt(val.trim(), 10);
  throw new ManifestError(
    `entry ${index}: position must be an integer, got ${JSON.stringify(val)}`,
  );
}

function toKeywords(val: unknown, index: number): readonly string[] {
  if (val === undefined || val === null) return [];
  if (!Array.isArray(val))
    throw new ManifestError(`entry ${index}: keywords must be an array of strings`);
  return val.map((k: unknown, j: number) => {
    if (typeof k !== "string")
      throw new ManifestError(`entry ${index}: keywords[${j}] must be a string`);
    return k;
  });
}

function validate(nodes: readonly ManifestNode[], files: readonly ManifestFile[]): void {
  const seen = new Set<string>();
  const dupes = new Set<string>();
  for (const n of nodes) {
    if (seen.has(n.stable_id)) dupes.add(n.stable_id);
    seen.add(n.stable_id);
  }
  if (dupes.size > 0) {
    const named = [...dupes]
      .sort()
      .map((d) => `'${d}'`)
      .join(", ");
    throw new ManifestError(`duplicate node stable_id(s): [${named}]`);
  }
  for (const n of nodes) {
    if (n.parent !== null && !seen.has(n.parent)) {
      throw new ManifestError(`node '${n.stable_id}': unknown parent '${n.parent}'`);
    }
  }
  for (const f of files) {
    if (!seen.has(f.node)) throw new ManifestError(`file '${f.path}': unknown node '${f.node}'`);
  }
  const paths = new Set<string>();
  for (const f of files) {
    if (paths.has(f.path)) throw new ManifestError("duplicate file paths in manifest");
    paths.add(f.path);
  }
}

/** Parents before children (insert order for the FK); a cycle fails loudly. */
export function topological(nodes: readonly ManifestNode[]): ManifestNode[] {
  const byId = new Map<string, ManifestNode>(nodes.map((n) => [n.stable_id, n]));
  const out: ManifestNode[] = [];
  const state = new Map<string, 1 | 2>(); // 1=visiting 2=done
  const visit = (n: ManifestNode): void => {
    const mark = state.get(n.stable_id) ?? 0;
    if (mark === 2) return;
    if (mark === 1) throw new ManifestError(`parent cycle at '${n.stable_id}'`);
    state.set(n.stable_id, 1);
    if (n.parent !== null) {
      const parent = byId.get(n.parent);
      if (parent === undefined) {
        throw new ManifestError(`node '${n.stable_id}': unknown parent '${n.parent}'`);
      }
      visit(parent);
    }
    state.set(n.stable_id, 2);
    out.push(n);
  };
  for (const n of nodes) visit(n);
  return out;
}

/**
 * The one canonical JSON emitter for every adapter (re-homed from the oracle's
 * `_to_json`, adapters/docusaurus_sidebar.py:410): node keys whose value is
 * null/empty/zero are omitted EXCEPT `position`, which is always emitted; file
 * dicts carry `title` only when set. Adapters round-trip the result through
 * `parseManifest` before writing, so an adapter can never emit what ingest
 * would refuse.
 */
export function manifestToJson(m: Manifest): Record<string, unknown> {
  return {
    format: m.format,
    corpus_id: m.corpus_id,
    source_commit: m.source_commit,
    nodes: m.nodes.map(nodeToJson),
    files: m.files.map((f) => ({
      path: f.path,
      node: f.node,
      ...(f.title ? { title: f.title } : {}),
    })),
  };
}

function nodeToJson(n: ManifestNode): Record<string, unknown> {
  const fields: readonly (readonly [string, unknown])[] = [
    ["stable_id", n.stable_id],
    ["slug", n.slug],
    ["title", n.title],
    ["kind", n.kind],
    ["parent", n.parent],
    ["position", n.position],
    ["summary", n.summary],
    ["keywords", n.keywords],
    ["permalink", n.permalink],
  ];
  const out: Record<string, unknown> = {};
  for (const [key, val] of fields) {
    const omit = val === null || val === 0 || (Array.isArray(val) && val.length === 0);
    if (key === "position" || !omit) out[key] = val;
  }
  return out;
}

/**
 * Carried verbatim from the oracle's build step (ingest/build.py:109):
 * `source_id = f.path.removesuffix(".md") + ":prose"`. The ".md"-only strip is
 * a deliberate quirk — `a/b.md` → `a/b:prose` while `a/b.mdx` KEEPS its suffix
 * → `a/b.mdx:prose`. Persisted source rows and carry-forward joins already pin
 * this shape; changing it is a policy decision, never a tidy-up.
 */
export function sourceId(path: string): string {
  return (path.endsWith(".md") ? path.slice(0, -3) : path) + ":prose";
}

export async function loadManifest(bundleDir: string): Promise<Manifest> {
  return parseManifest(await readFile(join(bundleDir, "manifest.json"), "utf8"));
}
