import { readFileSync } from "node:fs";
import { builtinModules } from "node:module";

import { defineConfig, type UserConfig } from "tsdown";

/**
 * The emitted checker carries the licences of what it bundles: `yaml` (ISC)
 * and `zod` (MIT), both of which require their notice to travel with copies.
 * The scaffold templates themselves stay MIT-0 (decision 10, revised by 26);
 * this file is a build product, not a template.
 */
function checkerBanner(): string {
  const notice = (pkg: string): string =>
    readFileSync(new URL(`./node_modules/${pkg}/LICENSE`, import.meta.url), "utf8").trim();
  return [
    "// GENERATED by the @panaversity/ksor package build from packages/content/src/record/ — do not edit.",
    "// The record's format rules as one program: bundled with the `yaml` parser (ISC) and `zod` (MIT).",
    "//",
    ...notice("yaml")
      .split("\n")
      .map((l) => `// yaml: ${l}`.trimEnd()),
    "//",
    ...notice("zod")
      .split("\n")
      .map((l) => `// zod: ${l}`.trimEnd()),
  ].join("\n");
}

const config: UserConfig[] = defineConfig([
  {
    entry: ["src/index.ts", "src/cli.ts", "src/gateway.ts"],
    platform: "node",
    dts: true,
    // ONE package (decision 12, publish revision 2026-08-20): the kernel is
    // bundled INTO the CLI — platform/content/gateway-kit/content-gateway are
    // inlined here, never published separately. Their external runtime deps
    // (pg, the MCP SDK, hono, jose, zod, yaml) are this package's deps.
    noExternal: [/^@panaversity\/ksor-/],
  },
  {
    // The emitted checker (record spec §6): self-contained, so an adopter's
    // CI runs it with bare node and no install. Everything but Node's own
    // modules is bundled; emit-checker.mjs copies the output into both skill
    // trees of the scaffold template after the build.
    entry: { "check-main": "src/check-main.ts" },
    outDir: "dist/checker",
    platform: "node",
    dts: false,
    deps: {
      alwaysBundle: (id) => !builtinModules.includes(id.replace(/^node:/, "")),
      onlyBundle: false,
    },
    banner: checkerBanner(),
  },
]);

export default config;
